# 16x16 pixel sprites. chars -> palette keys.
PAL = dict(o="#2A3230", O="#4A554E",            # outline / soft outline
           g="#55755B", G="#7E9B80", h="#A9C1A5", # moss dark/mid/light
           y="#B08A4A", Y="#D8B366", w="#F0DFAE", # ochre dark/mid/light
           c="#A5705A", C="#C6907A",              # clay
           s="#5A7B8C", S="#8DA9B8", b="#C7D8E0", # slate
           p="#8A6478", P="#B58FA0",              # plum
           k="#F5F3EC", d="#D8DCD5", n="#8E958B") # paper / sunk / dust

S = {}
S['coin'] = """
................
.....oooooo.....
...ooYYYYYYoo...
..oYYwwwwwwYYo..
.oYYwwYYYYwwYYo.
.oYwwYYyyYYwwYo.
.oYwYYyyyyYYwYo.
.oYwYYyyyyYYwYo.
.oYwwYYyyYYwwYo.
.oYYwwYYYYwwYYo.
..oYYwwwwwwYYo..
...ooYYYYYYoo...
.....oooooo.....
................
................
................
"""
S['sprout'] = """
................
................
.....oo....oo...
....ohho..ohho..
...ohhho.ohhho..
...ohhhoohhho...
....ohhoGohho...
.....oo.G.oo....
........G.......
........G.......
........G.......
.......oGo......
...oooooooooo...
...oGGGGGGGGo...
...oooooooooo...
................
"""
S['book'] = """
................
..oooooooooooo..
.osSSSSSSSSSSso.
.oSkkkkkkkkkkSo.
.oSkooooooookSo.
.oSkkkkkkkkkkSo.
.oSkoooooookkSo.
.oSkkkkkkkkkkSo.
.oSkooooookkkSo.
.oSkkkkkkkkkkSo.
.oSkoooookkkkSo.
.oSkkkkkkkkkkSo.
.osSSSSSSSSSSso.
..oooooooooooo..
................
................
"""
S['quill'] = """
............oo..
...........obbo.
..........obbSo.
.........obbSo..
........obbSo...
.......obbSo....
......obbSo.....
.....obbSo......
....obbSo.......
...obbSo........
..oSSo..........
..oSo...........
.ooo............
oo..............
................
................
"""
S['gavel'] = """
................
.........oooo...
........oyYYyo..
.......oyYYYyo..
......oyYYYyo...
.....oyYYYyo....
....ooyYyoo.....
...oyoyyo.......
..oyyoo.........
.oyyo...........
.oyo............
.oo.............
................
..oooooooooo....
..oyyyyyyyyo....
..oooooooooo....
"""
S['umbrella'] = """
................
.......oo.......
.....ooCCoo.....
...ooCCCCCCoo...
..oCCcCCCCcCCo..
.oCcCCcCCcCCcCo.
oCCCCCCCCCCCCCCo
oooooooooooooooo
.......oo.......
.......oo.......
.......oo.......
.......oo.......
.......oo.......
......ooo.......
.....ooo........
.....oo.........
"""
S['train'] = """
................
...oooooooooo...
..osSSSSSSSSso..
..oSbbboobbbSo..
..oSbkkookkbSo..
..oSbbboobbbSo..
..oSSSSSSSSSSo..
..oSkkSSSSkkSo..
..oSSSSSSSSSSo..
..ooooooooooo...
..oOo......oOo..
..ooo......ooo..
..o..........o..
................
................
................
"""
S['signal'] = """
................
....oooooooo....
....oddddddo....
....odkccdko....
....odccccdo....
....oddddddo....
....odkgggdo....
....odggggdo....
....oddddddo....
....oooooooo....
.......oo.......
.......oo.......
.......oo.......
.......oo.......
.....oooooo.....
.....oOOOOo.....
"""
S['sun'] = """
................
.......o........
.....o.o.o......
......ooo.......
...oooYYYooo....
....oYwwwYo.....
..o.oYwwwYo.o...
....oYwwwYo.....
...oooYYYooo....
......ooo.......
.....o.o.o......
.......o........
................
................
................
................
"""
S['drop'] = """
................
.......oo.......
.......oo.......
......obbo......
.....obbbbo.....
....obbSSbbo....
...obbSSSSbbo...
...obSSSSSSbo...
..obSSSSSSSSbo..
..obSSSSSSSSbo..
...obSSSSSSbo...
...oobSSSSboo...
.....oobboo.....
.......oo.......
................
................
"""
S['star'] = """
................
.......oo.......
.......ww.......
......owwo......
......owwo......
.oooooowwoooooo.
.owwwwwwwwwwwwo.
..owwwwwwwwwwo..
...owwwwwwwwo...
....owwwwwwo....
...owwoowwoo....
..owwo..owwo....
..ooo....ooo....
................
................
................
"""

S['bird'] = """
................
................
.........ooo....
........okkko...
.......okokko...
.......okkkko...
......ooookkoo..
.....oGGGGkoo...
....oGGGGGGo....
....oGGGGGo.....
.....oGGGo......
......ooo.......
.....o..o.......
....oo..oo......
................
................
"""
S['pot'] = """
................
.....oo...oo....
....ohho.ohho...
...ohhhoohhho...
...ohhhGGhhho...
....oohGGhoo....
.......GG.......
.......GG.......
....oooooooo....
....ocCCCCco....
....ocCCCCco....
.....occCCco....
.....occccco....
......ooooo.....
................
................
"""
S['droplet'] = """
................
.......oo.......
.......oo.......
......obbo......
......obbo......
.....obSSbo.....
.....obSSbo.....
....obSSSSbo....
....obSSSSbo....
....obSSSSbo....
.....obSSbo.....
......oooo......
................
................
................
................
"""

S['clock'] = """
................
.....oooooo.....
...ooddddddoo...
..oddddddddddo..
.oddddddddddddo.
.oddddddddddddo.
.oddddddoddddddo
.oddddddodddddd.
.oddddddoooodd..
.oddddddddddddo.
.oddddddddddddo.
..oddddddddddo..
...ooddddddoo...
.....oooooo.....
................
................
"""
S['arrow'] = """
................
................
................
................
................
........oo......
..oooooooYo.....
..oYYYYYYYYo....
..oYYYYYYYYYo...
..oYYYYYYYYo....
..oooooooYo.....
........oo......
................
................
................
................
"""
S['cloud'] = """
................
................
.....oooo.......
...oobbbboo.....
..obbbbbbbbo....
.obbbbbbbbbbo...
obbbbbbbbbbbbo..
oooooooooooooo..
..S...S...S.....
...S...S...S....
..S...S...S.....
................
................
................
................
................
"""

# ---- wide sprites (32x16) ----
W = {}
W['tram'] = """
................................
.............oo.................
....oooooooooooooooooooooo......
...osssssssssssssssssssssso.....
..ossSSSSSSSSSSSSSSSSSSSSsso....
..osSbbbbSbbbbSbbbbSbbbbSbso....
..osSbbwbSbbbbSbbwbSbbbbSbso....
..osSSSSSSSSSSSSSSSSSSSSSSso....
..oswwwwwwwwwwwwwwwwwwwwwwso....
..osSSSSSSSSSSSSSSSSSSSSSSso....
..osSSkkSSSSSSSSSSSSkkSSSSso....
..osssssssssssssssssssssssso....
...oooooooooooooooooooooooo.....
....oOo..........oOo............
....ooo..........ooo............
................................
"""

def to_svg(name, grid, w=16, h=16):
    rows=[r for r in grid.strip("\n").split("\n")]
    out=[f'<symbol id="px-{name}" viewBox="0 0 {w} {h}">']
    for y,row in enumerate(rows[:h]):
        x=0
        while x < min(len(row),w):
            ch=row[x]
            if ch in PAL:
                run=1
                while x+run<min(len(row),w) and row[x+run]==ch: run+=1
                out.append(f'<rect x="{x}" y="{y}" width="{run}" height="1" fill="{PAL[ch]}"/>')
                x+=run
            else:
                x+=1
    out.append('</symbol>')
    return "".join(out)

if __name__=="__main__":
    syms="\n".join(to_svg(n,g) for n,g in S.items())
    syms+="\n"+"\n".join(to_svg(n,g,32,16) for n,g in W.items())
    open("sprites.svg","w").write(
      '<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0"><defs>\n'+syms+'\n</defs></svg>')
    # preview
    n=len(S); cols=5; rows=(n+cols-1)//cols
    cell=96
    body=[]
    for i,name in enumerate(S):
        cx=(i%cols)*cell+8; cy=(i//cols)*(cell+18)+8
        body.append(f'<use href="#px-{name}" x="{cx}" y="{cy}" width="80" height="80"/>')
        body.append(f'<text x="{cx}" y="{cy+92}" font-family="monospace" font-size="11" fill="#2A3230">{name}</text>')
    open("preview.svg","w").write(
      f'<svg xmlns="http://www.w3.org/2000/svg" width="{cols*cell+16}" height="{rows*(cell+18)+16}">'
      f'<rect width="100%" height="100%" fill="#E4E7E3"/><defs>{syms}</defs>'
      f'<g shape-rendering="crispEdges">{"".join(body)}</g></svg>')
    print("sprites:",", ".join(S))
